name: Deploy Next.js to S3

on:
  push:
    branches:
      - main # Trigger on changes to the `main` branch
  pull_request:
    branches:
      - main # Trigger on PR to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 6: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 7: Deploy the exported static files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./out/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude ".git/*" --exclude ".github/*"
